# See: https://docs.github.com/ja/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions
# See: https://about.codecov.io/blog/getting-started-with-code-coverage-for-golang/
name: test
on:
  push:
    tags:
      - v*
    branches:
      - develop
      - main
  pull_request:
jobs:
  unit:
    name: unit
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ["1.18.x", "1.19.x", "1.20.x"]
        include:
          - go: 1.20.x
            latest: true
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - name: Test
        run: make cover
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2