# See: https://docs.github.com/ja/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions
name: test
on:
  push:
    tags:
      - v*
    branches:
      - develop
      - main
  pull_request:
jobs:
  unit:
    name: unit
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17'
      - name: Unit Test
        run: |
          go test ./... -v
